### ISSUE TITLE
Getting Inaccessible

### ISSUE THREAD

**Issue by JayantGoel001** [iampavangandhi/Gitwar#11]
Hello,
I don't what kind of issue i am getting in gitwar profile but it is showing Its Inaccessible
Kindly Help Me in that

**Comment by JayantGoel001** [comment]
It got solved
Thank you

**Comment by iampavangandhi** [comment]
@JayantGoel001 I am using a free heroku dyno for Gitwar as so many of you are using Gitwar it's monthly bandwidth is exhausted. You can deploy it on your heroku account to use it without any worry or wait for 2-3 days.

**Comment by JayantGoel001** [comment]
@iampavangandhi Actually I already deployed on my Heroku platform but it was Showing Inaccessible but its ok now.

**Comment by iampavangandhi** [comment]
@JayantGoel001 That's Great

**Comment by JayantGoel001** [comment]
@iampavangandhi 
I am again getting "Inaccesible"
This is most probably not related to band width 
Please give it a look.

https://gitwar-jayant.herokuapp.com/badge/?username=JayantGoel001

**Comment by iampavangandhi** [comment]
Hi @JayantGoel001 that error is because of the multiple instances of Gitwar. I am using ioshield for Gitwar badges. Will try to fix it in the next update.

Till then you can use the below URL

https://img.shields.io/badge/dynamic/json?label=Gitwar%20Profile%20Score&style=for-the-badge&color=0088cc&logo=github&logoColor=white&query=score&url=http%3A%2F%2Fgitwar-jayant.herokuapp.com%2Fapi%2FJayantGoel001
