### ISSUE TITLE
Website is Down

### ISSUE THREAD

**Issue by ksdkamesh99** [iampavangandhi/Gitwar#12]
Hi, @iampavangandhi  I loved your project and a big fan of your project. But for some days I am trying to access your website but it is down. Please check this issue and make it resolve fast. The Current Screenshot of your website where I am facing an error is 
![image](https://user-images.githubusercontent.com/46109386/103162660-602ee380-4819-11eb-811a-430354979288.png)

**Comment by ksdkamesh99** [comment]
Please do follow me on @ksdkamesh99

**Comment by iampavangandhi** [comment]
Hey, @ksdkamesh99 I am using a free tier of Heroku dyno for the project which comes with monthly limits as Gitwar is been used by many users the limit gets exhausted early. You can deploy this project on your own Heroku account for a seamless experience or you can wait for 3-4 days so that the limit will gets renewed.

Thank you

**Comment by ksdkamesh99** [comment]
Thanks @iampavangandhi
